### PR TITLE
Add reverse-string

### PR DESCRIPTION
**Pull request by BNAndras**

### CODE REVIEW

**Comment by BNAndras** [comment]
Compilation fails locally so this is a WIP.

**Comment by BNAndras** [comment]
@ErikSchierboom, I tested this with the test runner image locally and the tests all pass.

**Review by ErikSchierboom — APPROVED** [review]
Has a merge conflict

**Comment by BNAndras** [comment]
Merge fixed

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
