### PR TITLE
Add protein translation exercise

### PR DESCRIPTION
**Pull request by kahgoh**
Protein translation for 48in24

https://forum.exercism.org/t/48in24-exercise-02-13-protein-translation/9556

### CODE REVIEW

**Comment by BNAndras** [comment]
@ErikSchierboom, can you take a look at this and #187? Thanks

**Review by ErikSchierboom — APPROVED** [review]
Nice work

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Could you fix the merge conflict?

**Comment by kahgoh** [comment]
@ErikSchierboom I've justed fixed and pushed ;)

**Comment by ErikSchierboom** [comment]
Merge conflict is back, sorry!

**Comment by kahgoh** [comment]
@ErikSchierboom I've just merged and pushed

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
