### PR TITLE
github no longer supports git protocol

### PR DESCRIPTION
**Pull request by MenkeTechnologies**
https://github.blog/2021-09-01-improving-git-protocol-security-github/

### CODE REVIEW

**Comment by kotp** [comment]
Can you amend the commit for this and add the linked information and a summary to the commit?

**Comment by kotp** [comment]
The subject line may be misleading title may be misleading as well, as github does support the git protocol, it is deprecating the use of DSA keys, as one point.

**Comment by MenkeTechnologies** [comment]
March 15, 2022	Changes made permanent.
We’ll permanently stop accepting DSA keys. RSA keys uploaded after the cut-off point above will work only with SHA-2 signatures (but again, RSA keys uploaded before this date will continue to work with SHA-1). The deprecated MACs, ciphers, and unencrypted Git protocol will be permanently disabled.

https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by ErikSchierboom** [comment]
Is there anyone from @exercism/reviewers that knows LFE and can test this?

**Review by ee7 — APPROVED** [review]
I haven't tested, but this looks good to me. See https://rebar3.org/docs/configuration/dependencies/

With this PR, I've checked whether there is any remaining `git://`. It turns out there is one in a `rebar.lock` file:

```console
$ git grep --heading 'git:'
exercises/practice/anagram/rebar.lock
2:  {git,"git://github.com/rvirding/lfe.git",
```

https://github.com/exercism/lfe/blob/23e75cb1960d9fdbb99055ead70a35aa21a6f433/exercises/practice/anagram/rebar.lock#L1-L4

So I'll approve, but please change it there also (unless there's a reason not to). I don't know why that `rebar.lock` file has a different format to the others.

**Comment by MenkeTechnologies** [comment]
i changed to http:// in rebar.lock

**Review by ee7 — APPROVED** [review]
To others: the overall diff across the two force-pushes is as expected: [`23e75cb..b1eaf75`](https://github.com/exercism/lfe/compare/23e75cb1960d9fdbb99055ead70a35aa21a6f433..b1eaf7531243b8bd3a8472904e19ece828953a71).

**Review by kotp — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Merged. Thanks!

**Pull request merged**
