### PR TITLE
fix export list

### LINKED ISSUE #82: Fix the Hello World exercise so it passes with 'make test' on CI
I do not know if this is failing locally, but on Travis CI we are getting the following failure:

```
===> Compiling exercises/hello-world/src/hello-world.lfe failed
/home/travis/build/exercism/lfe/exercises/hello-world/src/hello-world.lfe:9999: unbound function: #(from 1)
make: *** [test] Error 1
The command "make test" exited with 2.
```

### PR DESCRIPTION
**Pull request by NobbZ**
FIX #82

### CODE REVIEW

**Comment by NobbZ** [comment]
Personally I'd prefer to not provide a stub that already passes the tests, instead I'd prefer to have a stub that already returns a string saying `"fix me"` or something like that.

But this PR is mean as a quickfix. And I wanted to keep changes small.

We should look into exercise architecture in a separate issue.

**Comment by NobbZ** [comment]
I've just seen that there are more issues, I think I have to do it locally then and not through GH UI.

**Comment by NobbZ** [comment]
Tests are green now.

**Comment by yurrriq** [comment]
Thanks for this, and for your patience!

**Pull request merged**
