### PR TITLE
Add Key Features and Icons.

### PR DESCRIPTION
**Pull request by astyanax**
References:
- [https://lfe.gitbooks.io/sicp/content/fm/preface-3/lfe.html](https://lfe.gitbooks.io/sicp/content/fm/preface-3/lfe.html)
- [https://learnxinyminutes.com/docs/lfe/](https://learnxinyminutes.com/docs/lfe/)
- [https://erlangforums.com/t/lfe-lisp-flavoured-erlang-have-you-used-it/179/20](https://erlangforums.com/t/lfe-lisp-flavoured-erlang-have-you-used-it/179/20)
- [https://lfe.io/](https://lfe.io/)

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Looking good. Juts needs a couple of tweaks to the length. See https://github.com/exercism/lfe/actions/runs/5734767189/job/15541463469#step:4:1

**Comment by astyanax** [comment]
Done @ErikSchierboom, thank you for your time :). Good opportunity to learn about Exercism's configlet. I'll try to [install and use its lint/fmt actions in the future](https://exercism.org/docs/building/configlet).

While I have your attention, 2 quick questions:

1) Existing config.json files have lines larger than 100, I assume this will be a problem with future PRs?
JSON doesn't support multi-line strings, so one really has to compact the text in this limited space. It took some time to fix mine without losing important information, it was a nice editing exercise.

2) I assume non-maintainers can no longer provide (trivial) suggestions in tracks, correct?
I noticed for example a typo in https://github.com/exercism/lua/blob/651978bebb6a9fc42e50297ac78996494c7e590b/config.json#L1142C26-L1142C36, but it sounds like it's more trouble than it's worth to fix it?

**Comment by ErikSchierboom** [comment]
> Existing config.json files have lines larger than 100, I assume this will be a problem with future PRs?

Do you have specific examples?

> I assume non-maintainers can no longer provide (trivial) suggestions in tracks, correct?

They can, but most tracks will see the PRs auto-closed. That said, if you have some minor fixes, feel free to ping me. I'd be happy to approve and merge a PR for the small typo you mentioned.

**Comment by astyanax** [comment]
Wonderful, cheers!

> Do you have specific examples?
So, I misunderstood the requirement: the `value` of `content` should be <= 100, not the full line, so all good!

All the examples I found (Perl, Prolog, Ruby, Python etc) had max content length between 95 and 100 characters (and some skipped `.` to gain that single character), so linting will be valid.

**Pull request merged**
