### PR TITLE
Add roman numerals exercise

### PR DESCRIPTION
**Pull request by kahgoh**
Note, this recreating a PR #188 after having to rebase a branch to update a different PR. This is one of the 48in24 exercises

https://forum.exercism.org/t/48in24-exercise-02-06-roman-numerals/9399/21

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
Nice!

**Comment by ErikSchierboom** [comment]
Could you fix the merge conflict?

**Comment by ErikSchierboom** [comment]
Sorry, another conflict

**Comment by kahgoh** [comment]
I've just pushed the update

**Pull request merged**
